<p style="color:#153462; 
          font-weight: bold; 
          font-size: 30px; 
          font-family: Gill Sans, sans-serif; 
          text-align: center;">
          Two dimentional Tensors</p>

In [1]:
import torch

In [2]:
import numpy as np
import pandas as pd

In [3]:
# Creating 2 dimentional tensor
data = [[2, 14, 45], [255, 123, 0], [45, 32, 224]]
tensor_data = torch.tensor(data)
tensor_data

tensor([[  2,  14,  45],
        [255, 123,   0],
        [ 45,  32, 224]])

In [4]:
# Checking dimention
tensor_data.ndimension()

2

In [5]:
# To check the shape
tensor_data.shape

torch.Size([3, 3])

In [6]:
tensor_data.size()

torch.Size([3, 3])

In [7]:
# To count total number of elements in the tensor
tensor_data.numel()

9

<p style="color:#3C4048; 
          font-weight: bold; 
          font-size: 18px; 
          font-family: Gill Sans, sans-serif;">
          Accessing Tensor 2D-Data:</p>

In [8]:
tensor_data

tensor([[  2,  14,  45],
        [255, 123,   0],
        [ 45,  32, 224]])

In [9]:
# Accessing entire row
tensor_data[0]

tensor([ 2, 14, 45])

In [10]:
# Accessing specific element
# Mean: 2nd row, 2nd column element
tensor_data[1, 1]

tensor(123)

In [11]:
tensor_data[1][1]

tensor(123)

In [12]:
# accessing entire column
tensor_data[:, 0]

tensor([  2, 255,  45])

In [13]:
# Accessing specific number of rows,
tensor_data[0:2]
#or
tensor_data[0:2, :]

tensor([[  2,  14,  45],
        [255, 123,   0]])

In [14]:
# Accessing specific number of columns,
tensor_data[:, 1:3]

tensor([[ 14,  45],
        [123,   0],
        [ 32, 224]])

### Tensor operations

In [15]:
# Tensor additions
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[3, 3], [4, 3]])

In [16]:
# Tensor addtion
a + b

tensor([[4, 5],
        [7, 7]])

In [17]:
# scalar multiplication
2*a

tensor([[2, 4],
        [6, 8]])

In [18]:
# Elementwise product
a*b

tensor([[ 3,  6],
        [12, 12]])

In [19]:
# Matrix multiplication
torch.mm(a, b)

tensor([[11,  9],
        [25, 21]])

<p style="color:#3C4048; 
          font-weight: bold; 
          font-size: 18px; 
          font-family: Gill Sans, sans-serif;">
          Conversion of tensor object into other objects and Vice Versa</p>

In [20]:
numpy_data = tensor_data.numpy()
print(F"Tensor to Numpy:\n {numpy_data}")
print(F"Data type of an numpy array: {numpy_data.dtype}")
print("=="*18)
new_tensor_data = torch.from_numpy(numpy_data)
print(F"From numpy array to Tensor:\n{new_tensor_data}")
print(F"Data type of an tensor: {new_tensor_data.dtype}")

Tensor to Numpy:
 [[  2  14  45]
 [255 123   0]
 [ 45  32 224]]
Data type of an numpy array: int64
From numpy array to Tensor:
tensor([[  2,  14,  45],
        [255, 123,   0],
        [ 45,  32, 224]])
Data type of an tensor: torch.int64


In [21]:
df = pd.DataFrame({"a": [1, 2, 3], "b": [3, 7, 5]})
torch.from_numpy(df.values)

tensor([[1, 3],
        [2, 7],
        [3, 5]])